version: "2"
services:
  test-scripts:
    build: .
    volumes: 
    - /Users/Dan/Desktop:/data
    environment: 
    - SELENIUM_HOST=selenium
    - SCREENSHOT_SAVE_PATH=/data/screenshot.png
    depends_on:
    - selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
    - "4444:4444"
