version: "2"
services:
  test-scripts:
    build: .
    volumes: 
    - /Users/Dan/Desktop:/data
    depends_on:
    - selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
    - "4444:4444"
